### ISSUE TITLE
Incorrect Page Linking for 'Locale' Option in INDEX.md Locations Section

### ISSUE THREAD

**Issue by Masked-Kunsiquat** [kevinkickback/Tashas-Notes-of-Everything#2]
First off - thank you for sharing this repo! I can't wait to use it in the upcoming campaign (this'll be my second go)!

# Issue Summary:
I'm experiencing an issue with the DataviewJS script in the "Locations" section of the `INDEX.md` file. Specifically, when I click on a link for a location under the "locale" category, it incorrectly directs me to a new page with a malformed name, such as {locale, instead of navigating to the correct existing page.

## Example:
For instance, if I have a file named `MyLocale.md` under the "locale" category, clicking the link in the "Locations" section should take me to that file. However, it instead creates or redirects to a page named `{MyLocale.md`, which doesn't exist.

## Issue Details:
- This issue appears to be specific to the "locale" option in the setup (plane, realm, continent, region, locale, landmark).
- Other categories like plane or realm seem to be working correctly without this issue.

# Environment:
- I'm using the recommended setup with all plugins and snippets as specified in the repository's instructions.

# Request:
- Could you provide guidance on why this might be happening or suggest further troubleshooting steps?

**Comment by kevinkickback** [comment]
Thank you for catching this. It's a simple typo that's breaking it. I'll push an update right now. If you would like to fix it yourself in your own vault you can do the following:

 1. Navigate to LOCALE.md in Assets/Templates
 2. Locate the line: `headerLink: "[[{<% name %>#<% name %>]]"`
 3. Remove the `{`

**Comment by Masked-Kunsiquat** [comment]
No, thank _you_ for this awesome repo, and your quick response!! 

everything's working flawlessly now - currently trying to make a Button to add creatures to a Bestiary (similar adding locations).

hope it's alright commenting questions once in awhile. thanks again!
