### ISSUE TITLE
Feature Request: Add Province Template

### ISSUE THREAD

**Issue by CSVincentS** [kevinkickback/Tashas-Notes-of-Everything#3]
**Description:** Currently, the vault lacks a template for managing provinces, which poses a limitation while making  notes of a region. Although there is a "Region Template" for larger areas, and a "Locale Template" for smaller locations, neither of these can be used to manage provinces. 

This request aims to address that gap by introducing a  **"Province Template"**, and modifying the **"Region Template"** and the **"Locale Template"**.

**Proposed Changes:**
**1. Add a Province Template:**
- Fields:
  - **Name**
  - **Type** (e.g., Province, State, County).
  - **Location**:  (e.g., Country, Kingdom, Nation).

- The Location Callout should be linked to **Locales**, meaning that a **Province** can contain one or more **Locales**.
  
**2. Modify the Region Template:**
- To better reflect the new structure, rename the **"Region Template"** to something like **"Territory Template"**, which would encompass larger regions such as countries, kingdoms, nations and general regions.
- The Location Callout should be linked to **Provinces**, meaning that a **Region** can contain one or more **Provinces**

**3. Modify the Locale Template:**
- A **Locale** is currently linked to a **Region**, but with the introduction of provinces, it should now be linked to **Provinces** instead.

**Comment by kevinkickback** [comment]
Great work. Merged.
